name: prometheus_project

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      # 1. 실제 prometheus.yml 파일이 있는 정확한 경로로 매핑하세요.
      # (만약 절대경로 /libs 라면 ./libs 가 아니라 /libs/prometheus.yml 로 수정)
      - ./libs/prometheus.yml:/etc/prometheus/prometheus.yml
      
      # 2. 데이터 유지를 위한 볼륨 추가 (과거 데이터 삭제 방지)
      - prometheus_data:/prometheus
      
    # 3. command 문법 수정 (한 줄로 명확하게 작성)
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"


  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    # prometheus 실행후 해야하기 때문에 종속성 설정(무조건 보장이되는건 아님)
    depends_on:
    -  prometheus


# 데이터 보존을 위한 별도 볼륨 선언
volumes:
  prometheus_data:


  