services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:9.4.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false

  kibana:
    container_name: kibana
    image: kibana:9.4.2
    ports:
      - "5601:5601"
    environment:
      # 오타 수정: ELASITCSEARCH -> ELASTICSEARCH
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    image: logstash:9.4.2
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
